#环境配置
server:
  port: 8001
  servlet:
    context-path: /hn_team_web
  tomcat:
    max-connections: 20000
    threads:
      max: 1000
spring:
  application:
    name: henan_team
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/upload,classpath:/static/upload,classpath:/static,classpath:/pic/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    # 服务器数据连接token删除失败
    host: 192.168.1.102
    port: 6379
    password: 123456
  # 服务器数据连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.102:5432/henanteam?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: 123456
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 200
    # 获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    # 检测连接是否失效的sql
    validation-query: SELECT 1
    # 检测连接是否失效的超时时间，单位：秒
    validation-query-timeout: 2
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filter:
      # 监控统计
      stat:
        enabled: true
        db-type: postgresql
        # 打印慢sql
        log-slow-sql: true
        # 超过2000毫秒即为慢sql,缺省值3000
        slow-sql-millis: 2000

mybatis-plus:
  mapper-locations: com/team/basic/dao/xml/*.xml,com/team/performance/dao/xml/*.xml,com/team/work/dao/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file:
    path: log
